
check:
  - thoth-precommit
  - thoth-build
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py36:v0.14.0
  build-stratergy: Source
  registry: "quay.io"
  registry-org: "thoth-station"
  registry-project: "graph-refresh"
  registry-secret: "thoth-station-thoth-pusher-secret"
deploy:
  project-org: "thoth-station"
  project-name: "thoth-application"
  image-name: "graph-refresh-job"
  overlay-contextpath: "graph-refresh/overlays/test/imagestreamtag.yaml"
