apiVersion: v1
kind: Template
labels:
  template: thoth-graph-refresh-cronjob
  thoth: 0.1.0
metadata:
  name: thoth-graph-refresh-job
  annotations:
    description: This is Thoth Core - Graph Refresh Job
    openshift.io/display-name: "Thoth: Graph Refresh Job"
    version: 0.1.0
    tags: poc,thoth,ai-stacks,graph
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This template defines resources needed to deploy Thoth Graph Refresh Job as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- kind: CronJob
  apiVersion: batch/v2alpha1
  metadata:
    name: graph-refresh
    namespace: ${THOTH_FRONTEND_NAMESPACE}
    labels:
      app: thoth-core
  spec:
    schedule: '*/30 * * * *'
    suspend: true
    concurrencyPolicy: Forbid
    successfulJobsHistoryLimit: 4
    failedJobsHistoryLimit: 4
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - image: graph-refresh
              name: graph-refresh
              env:
              - name: THOTH_JANUSGRAPH_HOST
                value: 'janusgraph'
              - name: THOTH_JANUSGRAPH_PORT
                value: '80'
              resources:
                requests:
                  memory: "32Mi"
                  cpu: "100m"
                limits:
                  memory: "128Mi"
                  cpu: "250m"
            restartPolicy: OnFailure

- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      app: thoth-core
    name: graph-refresh
    namespace: ${THOTH_FRONTEND_NAMESPACE}
  spec:
    name: latest
    lookupPolicy:
      local: true    

parameters:
- description: Name of the Thoth Frontend Namespace
  displayName: Thoth Frontend Namespace
  required: true
  name: THOTH_FRONTEND_NAMESPACE
